### ISSUE TITLE
TypeError: resolve is not a function

### ISSUE THREAD

**Issue by raduchiriac** [rollup/plugins#439]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 8.0.0
- Rollup Version: 2.13.1
- Operating System (or Browser): macOS 10.14.6
- Node Version: 12.16.0

### How Do We Reproduce?

I am trying to bundle Bootstrap using the configuration [here](https://github.com/twbs/bootstrap/blob/master/build/rollup.config.js) https://github.com/twbs/bootstrap/blob/master/build/rollup.config.js.

I get an error on line 30 saying that `resolve is not a function`. Bootstrap uses version 7.1.3 of this plugin, whereas I updated to the latest 8.0.0 and since then I get the said message

### Expected Behavior

v8.0.0 to bundle without any errors and work in the same way as v7.1.3 does

### Actual Behavior

I get an error: `TypeError: resolve is not a function`

**Comment by shellscape** [comment]
Looks like you need commonjs. Have you tried searching the issues here?

**Comment by raduchiriac** [comment]
> Looks like you need commonjs. Have you tried searching the issues here?

Yes I did, it might be similar to #412 but I am not 100% sure

**Comment by zebapy** [comment]
This works `const { nodeResolve } = require('@rollup/plugin-node-resolve');`

**Comment by raduchiriac** [comment]
Thanks @zebapy

**Comment by tborychowski** [comment]
I was having the same issue. Should the main readme be updated to indicate this change? The examples listed there don't work...

**Comment by zebapy** [comment]
@tborychowski there's a PR debating changes for that https://github.com/rollup/plugins/pull/456

**Comment by addod19** [comment]
Hi guys, am in a fixed currently, I have my store setup, actions, and reducers, also my form component where I send the dispatch action to the reducer. I get a `TypeError: Object(...) is not a function`. I have tried everything I can but it's probably I've not fully understood the technology. The following are my files
- Form component I connected with Redux with `connect`
```
import React, { useState } from 'react';
import { connect } from 'react-redux';
import addBrandCommission from '../redux/actions/brandCommissionActions';

const AddBrandCommission = () => {
  const [formData, setFormData] = useState({
    name: '',
    commission: '',
  });

  const { name, commission } = formData;

  const handleChange = (e) => setFormData({ ...formData, [e.target.name]: e.target.value });

  const handleSubmit = (e) => {
    console.log('hi me');
    e.preventDefault();
    if (formData) {
      console.log(formData);
      addBrandCommission({
        name,
        commission,
      });
      console.log('action is called, addBrandCommission');
      setFormData('');
    }
  };

  return (
    <>
      <h4>here, we will add commision here</h4>
      <form method="POST" onSubmit={handleSubmit}>
        <div className="form-group">
          <input type="text" name="name" value={name} onChange={handleChange} placeholder="Enter brand here" required />
        </div>
        <div className="form-group">
          <input type="decimal" name="commission" value={commission} onChange={handleChange} placeholder="Enter commission here" required />
        </div>
        <div className="form-group">
          <button type="submit" name="addBrandComission">Add Brand and Commission</button>
        </div>
      </form>
    </>
  );
};

export default connect(null, { addBrandCommission })(AddBrandCommission);

```
- This is my 'addForm' reducer function
```
import { ADD_BRANDCOMMISSION, BRANDCOMMISSION_ERRORS } from '../actions/actionTypes';

const initialState = [{
  name: 'Universal',
  commission: '12.8',
}];

const addBrandCommissionReducer = (state = initialState, action) => {
  const { type, payload } = action;
  console.log(action);
  switch (type) {
    case ADD_BRANDCOMMISSION:
      return {
        ...state,
        brandCommission: [
          {
            name: payload.name,
            commission: payload.commission,
          },
        ],
      };
    case BRANDCOMMISSION_ERRORS:
      return {
        ...state,
        error: payload,
        loading: false,
      };
    default:
      return state;
  }
};

export default addBrandCommissionReducer;

```
- [ ] Here is my actions
```
import { ADD_BRANDCOMMISSION, BRANDCOMMISSION_ERRORS } from './actionTypes';

const addBrandCommission = (brandCommission) => ({
  type: ADD_BRANDCOMMISSION,
  payload: { brandCommission },
});

const brandCommissionErrors = () => ({
  type: BRANDCOMMISSION_ERRORS,
});

export default { addBrandCommission, brandCommissionErrors };

```
- [ ] Here is my store
```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from './reducers';

const initialState = { };

const middleware = [thunk];

const store = createStore(
  rootReducer,
  initialState,
  compose(applyMiddleware(...middleware), // store enhancer func
  // eslint-disable-next-line no-underscore-dangle
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()),
);

export default store;

```
- [ ] Here is my actionTypes
```
export const ADD_BRANDCOMMISSION = 'ADD_BRANDCOMMISSION';
export const BRANDCOMMISSION_ERRORS = 'BRANDCOMMISSION_ERRORS';
export const LOGGEDIN = 'LOGGEDIN';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';
export const SET_USER = 'SET_USER';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

```
Thank you to anyone who will one way or the other share their knowledge about how to fix this code :man_technologist: :muscle:

**Comment by zebapy** [comment]
@addod19 you might want to post to a site like Stackoverflow with a minimal recreation of your app on codesandbox/codepen or similar. Your issue seems unrelated to the package in this repo and this specific github issue. 

After taking a quick look though, seems like you might be importing `addBrandCommission` wrong.

Try

```diff
import React, { useState } from 'react';
import { connect } from 'react-redux';
- import addBrandCommission from '../redux/actions/brandCommissionActions';
+ import { addBrandCommission } from '../redux/actions/brandCommissionActions';

```
