### ISSUE TITLE
`plugin-typescript` 12.1.3 cannot find modules with custom resolution logic

### ISSUE THREAD

**Issue by SquidDev** [rollup/plugins#1877]
- Rollup Plugin Name: Typescript
- Rollup Plugin Version: 12.1.3
- Rollup Version: 4.43.0
- Operating System (or Browser): Linux 6.15.1-arch1-2, 
- Node Version: 24.2.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-sbbqvy8r?file=rollup.config.js

### Expected Behavior
On `plugin-typescript` 12.1.2 and below, it was possible to use a plugin with `resolveId` and `declare module "xyz" { ... }` to load modules outside the standard resolution path (for instance, loading generated sources from elsewhere).

For instance, with the following in your `rollup.config.js`.

```javascript
    plugins: [
        typescript(),
        {
            name: "custom",
            async resolveId(source) {
                if (source === "test-module") return path.resolve("generated/test-module.js")
            }
        }
    ]
```

and the following declaration file:

```typescript
declare module "test-module" {
    export const sayHello: () => void;
}
```

Then it was possible to import `"test-module"` from a Typescript file.

### Actual Behavior
This no longer works under the recent 12.1.3 release (I assume this is introduced by #1653), failing with the following:

```
(!) [plugin typescript] src/index.ts (1:26): @rollup/plugin-typescript TS2307: Cannot find module 'test-module' or its corresponding type declarations.
rollup-demo/src/index.ts:1:26

1 import { sayHello } from "test-module";
                           ~~~~~~~~~~~~~
```

### Additional Information

It's possible I'm doing something utterly unspeakable and unsupported! I wasn't sure if this was an accidental breaking change or just Hyrum's law in action, so felt worth reporting.

**Comment by filipsobol** [comment]
We're encountering a similar issue. We use `@aws-sdk/client-bedrock-runtime`, which [overrides an import path](https://github.com/aws/aws-sdk-js-v3/blob/0f4697a8414473830b4eeae3cb88d309ee8659a3/clients/client-bedrock-runtime/package.json#L95-L97) when targeting browser environments which was respected by this plugin in `v12.1.2`.

However, starting with `v12.1.3`, it processes Node-specific files (that use dynamic imports which cause our build to fail), even though those files aren't actually used.

Here's a quick reproduction. The build fails with `v12.1.3` but works when downgrading to `v12.1.2`: https://stackblitz.com/edit/node-vsxkvtop?file=rollup.config.mjs,package.json

**Comment by mmomtchev** [comment]
Same for me, I have:

```js
{
  input: 'src/index.ts',
  output: {
    format: 'cjs',
    file: 'dist/cjs/index.cjs',
    sourcemap: true
  },
  plugins: [
    inject({
      fetch: 'node-fetch'
    }),
    typescript(),
    terser()
  ]
}
```

This allows me to use the native `fetch` in the browser and `node-fetch` in Node.js. With 12.1.3 I get:

```
[!] RollupError: src/tile.ts (1:9): "default" is not exported by "node_modules/node-fetch/lib/index.js", imported by "src/tile.ts".
```

`node-fetch` has a quite complex custom loading mechanism that has a CJS interface but sets manually `__esModule` to `true`.

If someone wants to take a look, here is the repo and the `dependabot` PR that triggered this:
https://github.com/mmomtchev/query-mvt/pull/266

**Comment by shellscape** [comment]
Fwiw this will require community contribution to be resolved.

**Comment by lukastaegert** [comment]
I created #1880 to revert the update for now as the issues appear to be widespread.
