### PR TITLE
fix(sucrase): use bare specifier to obtain SucraseOptions type

### PR DESCRIPTION
**Pull request by kherock**
## Rollup Plugin Name: `sucrase`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes
- [x] no (existing tests break after updating sucrase to 3.21.0)

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

When typechecking a TS project importing this plugin with `skipLibCheck: false`, a type error is thrown:

```
.yarn/__virtual__/@rollup-plugin-sucrase-virtual-7e2c8dc7a4/0/cache/@rollup-plugin-sucrase-npm-4.0.3-5d2d589
3b4-0f8a729c1b.zip/node_modules/@rollup/plugin-sucrase/types/index.d.ts:3:43 - error TS7016: Could not find 
a declaration file for module 'sucrase/dist/Options'. '/Users/.../.yarn/cache/sucrase-npm-3.21.0-78b7f0f024-
d686f255af.zip/node_modules/sucrase/dist/Options.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sucrase` if it exists or add a new declaration (.d.ts) file containing `decla
re module 'sucrase/dist/Options';`

3 import { Options as SucraseOptions } from 'sucrase/dist/Options';
                                            ~~~~~~~~~~~~~~~~~~~~~~
```

Sucrase v3.21.0 refactored its internal structure so that types are located apart from `dist`. I'm not sure why this specifier was chosen since Sucrase has always had this export available from the root specifier: [@alangpierce/sucrase@`ce0ec25...a2956ca` (diff)](https://github.com/alangpierce/sucrase/compare/ce0ec25b2204fcc0330023e0ef9d392c6efe19c4...a2956ca4cfb6b46ad9337e1f7e29cfa394ca53a7#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. Could you please add a types test similar to this: https://github.com/rollup/plugins/blob/master/packages/inject/test/types.ts

`package.json` will need to be updated like so:
https://github.com/rollup/plugins/blob/556837f0b7e7323f237370e36394569abc2b1ef9/packages/inject/package.json#L30
https://github.com/rollup/plugins/blob/556837f0b7e7323f237370e36394569abc2b1ef9/packages/inject/package.json#L23

**Review by shellscape — APPROVED** [review]
thanks!
