### PR TITLE
fix(typescript): revert #1653

### LINKED ISSUE #1877: `plugin-typescript` 12.1.3 cannot find modules with custom resolution logic
- Rollup Plugin Name: Typescript
- Rollup Plugin Version: 12.1.3
- Rollup Version: 4.43.0
- Operating System (or Browser): Linux 6.15.1-arch1-2, 
- Node Version: 24.2.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-sbbqvy8r?file=rollup.config.js

### Expected Behavior
On `plugin-typescript` 12.1.2 and below, it was possible to use a plugin with `resolveId` and `declare module "xyz" { ... }` to load modules outside the standard resolution path (for instance, loading generated sources from elsewhere).

For instance, with the following in your `rollup.config.js`.

```javascript
    plugins: [
        typescript(),
        {
            name: "custom",
            async resolveId(source) {
                if (source === "test-module") return path.resolve("generated/test-module.js")
            }
        }
    ]
```

and the following declaration file:

```typescript
declare module "test-module" {
    export const sayHello: () => void;
}
```

Then it was possible to import `"test-module"` from a Typescript file.

### Actual Behavior
This no longer works under the recent 12.1.3 release (I assume this is introduced by #1653), failing with the following:

```
(!) [plugin typescript] src/index.ts (1:26): @rollup/plugin-typescript TS2307: Cannot find module 'test-module' or its corresponding type declarations.
rollup-demo/src/index.ts:1:26

1 import { sayHello } from "test-module";
                           ~~~~~~~~~~~~~
```

### Additional Information

It's possible I'm doing something utterly unspeakable and unsupported! I wasn't sure if this was an accidental breaking change or just Hyrum's law in action, so felt worth reporting.

### LINKED ISSUE #1878: `plugin-typescript` 12.1.3 doesn't respect the `include` field in `tsconfig.json`
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version: 12.1.3
- Rollup Version: 4.31.0
- Operating System (or Browser): macOS Sequoia 15.5
- Node Version: 22.15.0
- Link to reproduction: https://github.com/toyobayashi/emnapi/actions/runs/15726909710. See `NPM Build` step

### Expected Behavior

Work well as 12.1.2.

### Actual Behavior

CI boom 💥

seems all declarations in separated `.d.ts` files no longer work, `const enum`s declared in .d.ts files not be replaced to constant in my source.

### Additional Information

plugin-typescript 12.1.3 doesn't respect the `include` field in tsconfig.json

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `typescript`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
- resolves #1877
- resolves #1878

### Description
This reverts #1653 as many users were experiencing issues. If we want the feature, a new attempt should be made that tests for the issues described in #1877 and #1878

### CODE REVIEW

**Comment by shellscape** [comment]
We're going to need a test to protect against future regressions that this revert fixes

**Comment by lukastaegert** [comment]
I added a test. Without the revert, the test fails because it gets a warning that no declaration for the external module can be found. With the revert, the declaration is found again.

**Comment by shellscape** [comment]
Perfect!
